name: Run Laravel Tests

on:
  pull_request:
    branches:
      - main
  pull_request_review:
    types: [submitted]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, dom, fileinfo, pdo, bcmath
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set up Database
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE testing;' -uroot -proot
          php artisan migrate --force

      - name: Run Tests
        run: php artisan test
