services:
    webserver:
        container_name: webserver
        build:
            context: .
            target: nginx-stage
        ports:
            - "8000:8000"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ../:/var/www/html
        depends_on:
            - php
        networks:
            - app-network

    php:
        container_name: php
        build:
            context: .
            target: php-stage
        restart: unless-stopped
        working_dir: /var/www/html
        depends_on:
            - mysql
        volumes:
            - ../:/var/www/html
            - ./entrypoint.sh:/usr/local/bin/entrypoint.sh

        networks:
            - app-network

    mysql:
        container_name: mysql
        image: mysql:8.4
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - "8080:80"
        environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - PMA_USER=user
        - PMA_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=root
        depends_on:
        - mysql
        networks:
        - app-network

volumes:
    mysql-data:

networks:
    app-network:
